
name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v3
    - name: Set Toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Run tests
      run: |
        sudo apt-get install -y protobuf-compiler
        rustup update
        cargo test